### PR TITLE
Fix for Missing Correct Plot Library Display

### PR DESCRIPTION
**Pull request by bsab**
This pull request addresses an issue with the correct plot library not displaying as intended due to an error that occurred during a previous merge. The error resulted in the display of incorrect or incomplete plots, which impacted the functionality of our data visualization features.

Changes implemented with this PR:
- [x] Corrected the merge error that was causing the problem by revisiting the conflicted files and ensuring the right code lines were kept.
- [x] Tests added and passed if fixing a bug or adding a new feature
- [x] All [code checks passed](https://github.com/gventuri/pandas-ai/blob/main/CONTRIBUTING.md#-testing).

## Summary by CodeRabbit

- **New Features**
	- Updated analysis process instructions, removing the requirement to save charts as images.
- **Documentation**
	- Updated code comments to reflect changes in visualization process.
- **Tests**
	- Adjusted test cases to match the updated analysis process instructions.
- **Style**
	- Made formatting changes to code comments for better readability.

### CODE REVIEW

**Comment by gventuri** [comment]
@bsab thanks a lot, but it's actually a change done on purpose. With the previous prompt, it was hallucinating much and most of the times it was returning a chart also for non-chart related prompts. Moving it into the "instructions" part of the prompt seems to have reduced this hallucination.

Let me know your thoughts :)

**Comment by bsab** [comment]
@gventuri  okay, maybe the hallucination phenomenon occurred because I tested the feature only with Azure OpenAI, but as for the feature itself, I can't get it to work with version 1.4.5. 

For example, if I set:

`df = SmartDataframe(df, config={"llm": llm, "enable_cache": False, "data_viz_library": "plotly"})`

the type of chart continues to be matplotlib. 

What step am I doing wrong?

**Comment by gventuri** [comment]
@bsab interesting that the results are not consistent across OpenAI and Azure. Which model are you using?
I'm working on a way to improve it and not forcing it to rely on the LLM to decide which library to use, will keep you posted!

**Comment by bsab** [comment]
@gventuri I've used gpt-4 and gpt-4-32k on Azure OpenAI

**Pull request closed without merging**
