### PR TITLE
feat(callbacks): add file callback

### LINKED ISSUE #364: Code generation
### 🚀 The feature

Is there a feature that enables to save the code generated after asking the question?

### Motivation, pitch

The reason I am asking this as an feature is sometimes the code generated is not able to run the code with the data.

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mspronesti**
- [X] closes #364 
- [X] All [code checks passed](https://github.com/gventuri/pandas-ai#contributing).

## Supposed usage
```py
from pandasai import PandasAI
from pandasai.llm.openai import OpenAI
from pandasai.callbacks import FileCallBack

cb = FileCallBack(filename="generated.py")
llm = OpenAI()

df = ... # <-- define your df here
question = "..." # <-- your question here!

pandas_ai = PandasAI(llm, callback=cb)
response = pandas_ai(df, question)
```

### CODE REVIEW

**Comment by gventuri** [comment]
@mspronesti super nice addition and great use case for the callbacks! Thanks a lot, merging!

**Comment by gowthaml15** [comment]
Hi @mspronesti, I couldn't able to import the FileCallBack function. 
image

**Comment by mspronesti** [comment]
@gowthaml15 it's because @gventuri renamed `FileCallBack` to `FileCallback` (lower case "b") before merging the PR. Try again with the right spelling :)

**Comment by gowthaml15** [comment]
@mspronesti, I tried with the lower case "b", That is also throwing me error. 
image
I tried to look into the installed location the file.py file is missing
image
The current version I am using is 
image

**Comment by gventuri** [comment]
@mspronesti thanks a lot for the fix 🚀 
@gowthaml15 it's now available as of version 0.7.2!

**Pull request merged**
