### PR TITLE
feat: add Sourcey as a quality gate tool in CI

### LINKED ISSUE #667: Insert a quality gate on CI
@gventuri, I've got some options for that.

We can use either [Sourcery](https://docs.sourcery.ai/Welcome/) or [SonarCloud](https://www.sonarsource.com/products/sonarcloud/)

Both are free for open-source projects. A lot of minor issues have already been caught by the SonarLint VSCode extension.

And after solving those that make sense, we should keep track of new codes to control them on the quality gate.

What do you think about it?

We can break this into tasks:
- Resolve SonarLint and/or mypy issues that make sense to solve
- Implement one of the two quality gates. My vote is for Sourcery on CI; it already has a [GitHub Actions](https://github.com/marketplace/actions/sourcery-action)

### PR DESCRIPTION
**Pull request by HenriqueAJNB**
- [x] closes #667
- [x] Tests added and passed if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://github.com/gventuri/pandas-ai/blob/main/CONTRIBUTING.md#-testing).
- [ ] Decide if manual refactoring make sense

@gventuri

I've completed this task, but there are still some manual refactorings that Sourcery couldn't do it. Maybe we should decide if it makes senses to accept and refactor its suggestions before proceeding with this PR approval.

```bash
$ sourcery review --fix pandasai
pandasai\helpers\code_manager.py:597-673 low-code-quality
pandasai\smart_dataframe\__init__.py:235-312 low-code-quality
pandasai\smart_datalake\__init__.py:281 avoid-builtin-shadow
pandasai\agent\__init__.py:71-71 raise-specific-error
pandasai\connectors\sql.py:44-44 raise-specific-error
pandasai\helpers\query_exec_tracker.py:269-269 raise-specific-error


─────────────────────────────────────────────────────────────────────────────── Overview ────────────────────────────────────────────────────────────────────────────────
 • 71 files scanned.
 • 6 issues detected.

Issues by Type

 • 0 issues were fixed by Sourcery.
 • 6 issues need to be fixed manually.

Issues by Rule ID
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┓
┃ Rule ID              ┃ Count ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━┩
│ raise-specific-error │     3 │
│ low-code-quality     │     2 │
│ avoid-builtin-shadow │     1 │
├──────────────────────┼───────┤
│ Total                │     6 │
└──────────────────────┴───────┘
```

And the CI has two options available for running: 
- Entire codebase
- Only on lines changed in future PRs

Since it's the first quality gate, I've decided to go for all the codebase. But once all fixes are made (or ignored), we can run it just on changed lines to be less CI time consuming.

## Summary by CodeRabbit

- New Feature: Integrated Sourcery AI into the workflow for code quality checks and added its configuration to the project.
- Refactor: Simplified and improved code readability across multiple files, including `pandasai/__init__.py`, `pandasai/agent/__init__.py`, `pandasai/connectors/base.py`, and others.
- Bug Fix: Enhanced error handling and exception messages in various files like `pandasai/connectors/airtable.py`, `pandasai/helpers/path.py`, `pandasai/prompts/file_based_prompt.py`, and more.
- Style: Updated code formatting and indentation in `.pre-commit-config.yaml` and several other files for better readability.
- Chore: Updated CI/CD workflow with a new job and simplified commands in `.github/workflows/ci.yml`.

### CODE REVIEW

**Comment by HenriqueAJNB** [comment]
I've left ruff some more flexible with 89 line length by adding two `# noqa: E501` to avoid failures. Now all checks except the `review-with-sourcery` is passing.

Perhaps it has something to do with credentials. Did you added the token @gventuri?

**Comment by gventuri** [comment]
@HenriqueAJNB yes, I checked it out and I confirm the SOURCERY_TOKEN secret has been set.

**Comment by HenriqueAJNB** [comment]
@gventuri, I'll investigate this sourcery authentication failure. 

Maybe we can even schedule a meeting to solve this together, which would be much better...

**Comment by gventuri** [comment]
@HenriqueAJNB I'm trying to remove it from the CI and using the Sourcery app instead. Merging the refactoring first, if this solution doesn't work we can then submit an additional PR and try to fix the CI!

**Pull request merged**
