### PR TITLE
feat(openai-callback): add Azure OpenAI fine-tuned models

### PR DESCRIPTION
**Pull request by mspronesti**
Completion of #682, plus some tests covering the cost computation for both OpenAI and Azure OpenAI - including fine-tuned models.

- [X] Tests added and passed if fixing a bug or adding a new feature
- [X] All [code checks passed](https://github.com/gventuri/pandas-ai/blob/main/CONTRIBUTING.md#-testing).

### Summary by CodeRabbit

- New Feature: Introduced a function to standardize model names, enhancing the consistency of interactions with the OpenAI API.
- Improvement: Updated the cost calculation and checking process to use the new standardized model names, improving the accuracy of cost estimations.
- Test: Added comprehensive test cases for the OpenAI Callback Handler, increasing the reliability of the system by ensuring it handles various model names and calculates costs correctly.

### CODE REVIEW

**Comment by gventuri** [comment]
@mspronesti thanks a lot, super cool changes! Merging :)

**Comment by mspronesti** [comment]
@gventuri Thanks for merging! Just be careful that you are no longer squashing commits before merging (check the commit history). If this was not intentional, I suppose you might want to rebase, otherwise just ignore this comment :)

**Comment by gventuri** [comment]
@mspronesti thanks a lot for reporting. That was actually unintentional, thanks for mentioning :)

**Comment by mspronesti** [comment]
I think it was also the case for the previous one or two PRs, but I suppose it's no big deal!

**Pull request merged**
