### PR TITLE
Feature/docs

### PR DESCRIPTION
**Pull request by amjadraza**
- [x]  #94  (#94 with the GitHub issue number)
- [x] The recent release 0.2.13 is merged with this PR
- [x] Documentation Set up added using `mkdocs` with `.md` support
- [x] We have adopted `readthedocs` template.
- [x] All [code checks passed](https://github.com/gventuri/pandas-ai#contributing).
- [ ] The base code is not touched. However, we have to have some refactoring of `docstrings` using Google Style Docstrings. 
- [ ] The documentation will be hosted on `readthedocs` server from Release Branch.
- [ ] Add Link to the Documentation Link and Badge to the main `README.md` file

Happy to discuss the PR in details if needed. Please refer to #94 for more details and discussions.

### CODE REVIEW

**Comment by gventuri** [comment]
Hey @amjadraza, thanks a lot for the PR! I'm just struggling to figure out why most of the files are overridden with exactly the same file. Could you explain?

**Comment by amjadraza** [comment]
I just pulled the latest versions and accepted the files from LATEST realese while merging.

**Comment by amjadraza** [comment]
@gventuri What do you recommend to change?

**Comment by gventuri** [comment]
@amjadraza not sure I understand why there are 52 files in the changes while it seems there is no actual change in most of them. Can we omit them from the PR or am I missing something?

**Comment by amjadraza** [comment]
@gventuri let me create a Fresh Copy and submit a MR again. Closing this for now.

**Pull request closed without merging**
