### PR TITLE
interpret json when llm returns json code

### PR DESCRIPTION
**Pull request by avelino**
fixed: #32

### CODE REVIEW

**Comment by gventuri** [comment]
Hey @avelino, thanks a lot for the great job!

I'd just ask you if you can also provide a test for this specific use case. Not that we have done a great job so far, but as the project grows, we should find a way to improve our coverage. What do you think?

**Comment by avelino** [comment]
@gventuri I believe the test is validating

**Comment by avelino** [comment]
@gventuri did you remove the `import json`?

**Comment by gventuri** [comment]
@avelino yes, as the response as of now is a json string, no need to import json library from what I've seen.

The error that I could find was about a different issue:
```
result = "{ param: '', param2: '' }"
print(result)
```

In fact, we intercept `print` calls and try to return `result`, but it wasn't defined because of a wrong implementation and so it was raising error.

However, if you want we can add support for json and in that case convert it to a dict.

Let me know what you think, I'd like to be more specific if my explanation wasn't clear.

**Pull request merged**
