### PR TITLE
fix TypeError: Cannot setitem on a Categorical with a new category (#…

### LINKED ISSUE #143: TESTING PANDAS AI with TITANIC Dataset: Getting Error
### 🐛 Describe the bug

Hello

Here is the code and I try to use it with the famous titanic daaset of seaborn library and it is throwing the following error. Can you advise Please:

Error:
TypeError: Cannot setitem on a Categorical with a new category (nan), set the categories first

Code:

import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#imorting pandas ai library
from pandasai import PandasAI
from pandasai.llm.starcoder import Starcoder

Instatiate a LLM
from pandasai.llm.openai import OpenAI
llm = Starcoder(api_token="my API key removed due to privacy")

#here goes ny dataset
df = sns.load_dataset('titanic')

pandas_ai = PandasAI(llm)
response = pandas_ai.run(df, "Top ten highest fare")

### PR DESCRIPTION
**Pull request by sandiemann**
…143)

- [x] closes #143
- [x] added test
- [x] All [code checks passed](https://github.com/gventuri/pandas-ai#contributing).

### CODE REVIEW

**Comment by sandiemann** [comment]
After the fix:
```
import pandas as pd
import seaborn as sns

#imorting pandas ai library
from pandasai import PandasAI
from pandasai.llm.starcoder import Starcoder

llm = Starcoder()

#here goes ny dataset
df = sns.load_dataset('titanic')

pandas_ai = PandasAI(llm)
response = pandas_ai.run(df, "Top ten highest fare")
print(response)
```

Output:
```
Question: Top ten highest fare
Answer: The top ten highest fares are 512.3292, 512.3292, 512.3292, 512.3292, 512.3292, 512.3292, 512.3292, 512.3292
```

**Comment by gventuri** [comment]
Great job @sandiemann! Could you maybe only enforce this with a test? Thanks a lot for the great contribution!

**Comment by sandiemann** [comment]
Sure! do you want me to add a test case with NaNs category column?

**Comment by gventuri** [comment]
@sandiemann yes, something that in the past was breaking PandasAI and now works thanks to your fix!

**Pull request merged**
