### PR TITLE
add parquet example to pandas-ai

### PR DESCRIPTION
**Pull request by tanersekmen**
## Summary by CodeRabbit

- **New Features**
  - Added an example of using PandasAI with a Parquet file, demonstrating the instantiation of a SmartDataframe with a Parquet file and a subsequent chat interaction to retrieve information.

### CODE REVIEW

**Comment by gventuri** [comment]
@tanersekmen something is failing in the CI, can you check it out before I can merge?

**Comment by tanersekmen** [comment]
hello @gventuri, I will check this out. Thank you 🙏

**Review by tanersekmen — COMMENTED** [review]
add pyproject.toml
update examples.md and from_parquet.py

**Comment by gventuri** [comment]
@tanersekmen still failing: https://github.com/gventuri/pandas-ai/actions/runs/7461343274/job/20303285800?pr=855

**Pull request merged**
