### PR TITLE
Optional installs instructions

### PR DESCRIPTION
**Pull request by mspronesti**
Playing around with Google PaLM, I run into an exception due to the missing dependency (I forgot we made it optional😄). I realized we never provided instructions on how to install it "since the beginning".

### CODE REVIEW

**Comment by gventuri** [comment]
Great catch @mspronesti! Should we rather move it to the documentation and mentioning it in the readme, then reminding to the documentation for more info? What do you think?

**Comment by mspronesti** [comment]
I guess every change we make to the README is reflected in the documentation, doesn't it ? 
https://github.com/gventuri/pandas-ai/blob/4fc3c02a27ea635558a364cc7c0203618a0e543b/docs/index.md?plain=1#L11

**Comment by gventuri** [comment]
@mspronesti, the `Getting started` section sounds ok for now. Hopefully at some point in the future we'll structure the docs a little bit better, but for now it's great!

P.s. thanks for the hint, just added!

**Comment by mspronesti** [comment]
@gventuri  done :)

**Comment by gventuri** [comment]
@mspronesti thanks a lot! Great job, merging!

**Pull request merged**
