### PR TITLE
Improve prompt

### LINKED ISSUE #97: How to read an existing dataframe
### 🐛 Describe the bug

The generated code expects a file_name.csv, as shown in the example below, How to read an existing dataframe. i'm running in jupyter notebook

Running PandasAI with openai LLM...

Code generated:
```
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('nama_file.csv')
suspicious_df = df[df['Is Laundering'] == 1]
for currency in suspicious_df['Receiving Currency'].unique():
    currency_df = suspicious_df[suspicious_df['Receiving Currency'] == currency
        ]
    plt.scatter(currency_df['Amount Received'], currency_df['Amount Paid'],
        label=currency)
plt.xlabel('Amount Received')
plt.ylabel('Amount Paid')
plt.legend()
plt.show()
```

### PR DESCRIPTION
**Pull request by yzaparto**
Changelog 
Fixes #97

### CODE REVIEW

**Review by Lorenzobattistela — COMMENTED** [review]
I think we need to change tests for this to run, because it will use the literal string

**Comment by gventuri** [comment]
@yzaparto thanks a lot for the MR. How did you benchmark the improvement, if I can ask and how do you think this implementation reduces the hallucination?

Also, as @Lorenzobattistela pointed out, tests are failing, let's make sure to also change them accordingly.

**Review by gventuri — CHANGES_REQUESTED** [review]
Let's also change the tests! :)

**Comment by gventuri** [comment]
@yzaparto did you have a chance to look into it?

**Pull request closed without merging**
