### PR TITLE
feat(skill): redesign skills and fix code exec env bug

### LINKED ISSUE #839: NameError: name 'pandasai' is not defined
### System Info

pandasai 1.5.11 (latest at the time the issue was opened) 
Python 3.10

### 🐛 Describe the bug

The skills logic is broken in the latest version of pandasai. This is due to the fact that no identifier is added to the `SkillManager` when the abstract syntax tree is parsed.

### PR DESCRIPTION
**Pull request by mspronesti**
Hi @gventuri,
this PR aims at making `Skill` a proper, pythonic type while supporting a (proper) decorator. This new implementation requires (purposely) the function to have a docstring when decorated with `@skill`. In addition, one can create a skill as follows

```py
skill = Skill.from_function(func=some_func, description=...)
```

- [X] Tests added and passed if fixing a bug or adding a new feature
- [X] Closes #839 
- [X] All [code checks passed](https://github.com/gventuri/pandas-ai/blob/main/CONTRIBUTING.md#-testing).

## Summary by CodeRabbit

- **Refactor**
  - Streamlined the process for adding skills to the system.
  - Enhanced the logic for SQL comparison extraction.
  - Improved the `Skill` class with new creation methods and properties.
  - Updated the handling of skills within the SmartDataframe class.

- **Bug Fixes**
  - Fixed incorrect type hints and method return types.

- **Tests**
  - Refined test cases for skill addition and prompt display functionalities.

- **Documentation**
  - Added docstrings to clarify the purpose of test functions.

### CODE REVIEW

**Comment by gventuri** [comment]
@mspronesti thanks a lot for the PR, great improvement. Can I review it or is it still on draft?

**Comment by mspronesti** [comment]
Hi @gventuri, feel free to review :) This PR is currently a draft because I have not updated the documentation yet.

**Comment by mspronesti** [comment]
@gventuri Ready :) I also solved #839.

**Comment by mspronesti** [comment]
@gventuri ready to go :) 
I've also added the option to specify a custom name for the skill and fixed the skill example (which was not working).

**Comment by gventuri** [comment]
@mspronesti thanks a lot, great changes (and thanks for fixing the skills, I should probably enforce with more tests to make sure this is more robust and cannot easily be broken)! 🚀

**Pull request merged**
