### PR TITLE
fix: rephrase query

### LINKED ISSUE #821: Agent rephrase_query Error
### System Info

pandasai version: 1.5.9

### 🐛 Describe the bug

using latest pandasai version(1.5.9) for rephrase_query, i'm getting the below error.

Code Snippet::
```
config = {
    "llm": llm
}
agent= Agent(dfs, config=config, memory_size=10)
response = agent.rephrase_query(question)
print(response)
```

Error::
```
Unfortunately, I was not able to repharse query, because of the following error:
'RephraseQueryPrompt' object has no attribute 'conversation_text'
```

### PR DESCRIPTION
**Pull request by Pranab1011**
- [ ] Closes #821 
- [ ] Tests added and passed if fixing a bug or adding a new feature.
- [ ] All [code checks passed](https://github.com/gventuri/pandas-ai/blob/main/CONTRIBUTING.md#-testing).

## Summary by CodeRabbit

- **New Features**
	- Enhanced the conversation templates in the app to include data frame and query information when available.
- **Refactor**
	- Improved code readability in the query rephrasing module.

### CODE REVIEW

**Comment by gventuri** [comment]
@Pranab1011 thanks a lot for the fix. However, it feels like tests are failing on windows. Can you check it out, then I'll merge it :D Thanks a lot again!

**Comment by Pranab1011** [comment]
@gventuri 
Let me check it out

**Comment by gventuri** [comment]
@Pranab1011 mmh that's a good point, honestly have no clue either. Seems to be an issue about encoding, but it's tough to debug without a windows computer. Maybe some prints, but it's not super straightforward. What are your takes on this?

**Comment by Pranab1011** [comment]
@gventuri I have added an encoding argument which should theoretically solve the issue unless there is a deeper problem here.

**Comment by Pranab1011** [comment]
@gventuri 
I guess this is good for merging

**Comment by gventuri** [comment]
@Pranab1011 thanks a lot, works now :)

**Pull request merged**
